# Generated by Django 4.0.4 on 2022-12-20 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("titles", "0003_alter_title_fee_paid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="title",
            old_name="created_date",
            new_name="creation_date",
        ),
    ]
