# Generated by Django 4.0.4 on 2022-12-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0004_rename_created_date_title_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='fee_paid',
            field=models.CharField(choices=[('y', 'y'), ('n', 'n')], max_length=20),
        ),
    ]
